name: sse_channel
description: StreamChannel wrappers for Server Sent Events.
version: 0.1.0
repository: https://www.github.com/jamiewest/sse_channel
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  async: ^2.11.0
  http: ^1.1.0
  pool: ^1.5.1
  sse: ^4.1.2
  stream_channel: ^2.1.1
  uuid: '>=3.0.7 <5.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.4
