name: data_repository
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.3
  firebase_core: ^2.4.1
  firebase_core_platform_interface: ^4.5.2
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  meta: ^1.7.0
  cloud_firestore: ^4.3.1
  provider: ^6.0.1

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


dependency_overrides:
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  flutter_bloc: ^8.1.1