name: Flutter Web Build
on:
  pull-request:
      - main
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: 'stable'
          cache: true
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: flutter build web --release
      - name: Build web
        run: |
          cd build/web